# Generated by Django 4.2.26 on 2025-12-03 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_equipo', models.CharField(max_length=100)),
                ('codigo_sesion', models.CharField(max_length=20)),
                ('carrera', models.CharField(blank=True, max_length=100, null=True)),
                ('integrantes', models.JSONField(default=list)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
