# Generated by Django 4.2.26 on 2025-12-03 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipo',
            old_name='integrantes',
            new_name='nombre',
        ),
    ]
