# Generated by Django 4.2.26 on 2025-12-03 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_integrantes_equipo_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='nombre',
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrantes', to='api.equipo')),
            ],
        ),
    ]
